### ISSUE TITLE
PDF of homework and exercises appears twice

### ISSUE THREAD

**Issue by jelgerjansen** [open-ideas/__CrashCourse__#15]
The pdf version of the homework appears twice in the corresponding directories: one time in the Homework directory itself and one time in the Homework/Latex directory.

**Comment by jelgerjansen** [comment]
@JavierArroyoBastida Lucas proposed to remove the Latex subdirectory and have all latex files (including the pdf) in the 'main' homework or exercise folder. Do you agree?

**Comment by JavierArroyoBastida** [comment]
I like how it is now with a dedicated latex folder in each homework/exercise directory. It is true that exercises 3 and 4 do not have any additional files/folders other than the latex files, but may still be useful to keep it like this since students may add their own files there. So I'd just remove duplicates.

**Comment by jelgerjansen** [comment]
If we have only a Latex directory, some students might be confused and cannot find the exercise notes, don't you think?
